name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master # Deploy only in maste branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          scripts: |
            cd /apps/MovieApp # Where is the project
            git pull origin master
            docker-compose down --remove-orphans
            docker-compose up --build -d
