name: Build Frontend (deveop)
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: MovieWEB/node_modules
          key: ${{ runner.os }}-MovieWEB-${{ hashFiles('MovieWEB/package-lock.json') }}
      - name: Install dependencies
        run: npm install
        working-directory: ./MovieWEB
      - name: Build Docker Image
        run: docker build -t frontend-image-develop ./MovieWEB
